version: '3.8'

services:
  mi-astro-app:
    build: .
    container_name: mi-astro-app
    restart: unless-stopped
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://EventosUTA_owner:npg_X3Zey2knOlfD@ep-nameless-queen-ach5gx2n-pooler.sa-east-1.aws.neon.tech/EventosUTA?sslmode=require
      - AUTH_SECRET=dfd34e83f5ab41ff0a3eafdf8ace99a7
      - AUTH_TRUST_HOST=true
      # Para Coolify + Cloudflare
      - AUTH_ORIGIN=https://eventouta.sjproyects.tech
      - NEXTAUTH_URL=https://eventouta.sjproyects.tech
      # Para que Auth.js sepa que está detrás de un proxy HTTPS
      - FORWARDED_HOST=eventouta.sjproyects.tech
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - CLOUDINARY_CLOUD_NAME=dwwvecqnu
      - CLOUDINARY_API_KEY=768872357128941
      - CLOUDINARY_API_SECRET=Z7yF6Cfv9wnZl9Tpep9jOBjKxso
      - VERIFALIA_SID=brayan7102
      - VERIFALIA_AUTH_TOKEN=brayanstiv2002
