version: '3.8'

services:
  mi-astro-app:
    build: .
    container_name: mi-astro-app
    restart: unless-stopped
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
      - PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Y2FyZWZ1bC1lYXJ3aWctMjAuY2xlcmsuYWNjb3VudHMuZGV2JA
      - CLERK_SECRET_KEY=sk_test_x9r0RrwKJOZp6KZ1AvMAKwlXYGc6TtAbf4zSNGPPtZ
      - DATABASE_URL=postgres://postgres:2lrGAGDus24ESi0I28AQQh7Sslch2mUyD6OYAF6RAC18imV4L3uCkwbwtzGqQKNG@mi-app-db:5432/postgres
      - AUTH_SECRET=dfd34e83f5ab41ff0a3eafdf8ace99a7
      - AUTH_TRUST_HOST=true
      - AUTH_ORIGIN=http://localhost:4321
      - CLOUDINARY_CLOUD_NAME=dwwvecqnu
      - CLOUDINARY_API_KEY=768872357128941
      - CLOUDINARY_API_SECRET=Z7yF6Cfv9wnZl9Tpep9jOBjKxso
      - VERIFALIA_SID=brayan7102
      - VERIFALIA_AUTH_TOKEN=brayanstiv2002
      - AUTH_ORIGIN=http://localhost:4321 
